### PR TITLE
Feature/updating schemas

### PR DESCRIPTION
**Pull request by guymcmanusgithub**
Added product schema, adding transaction schema, updating member schema.
Added tests for products and transaction
Added some basic publications for products and transactions to get all items in the collections
Added empty methods and methods.test files for both products and transactions as these will be required later on

### Done Checklist

* [ ] Task has been completed as per the Trello card
* [ ] All acceptance criteria are met
* [ ] Developer has tested this locally
* [x] Developer has reviewed their own PR
* [ ] Design has been reviewed by design team
* [x] Tests have been added or updated
* [ ] Views are responsive for mobile devices
* [ ] Feature files have been written or updated
* [x] Changelog updated

### CODE REVIEW

**Comment by mikkelking** [comment]
Guy,

This looks good, just a couple of things to tidy up...

1) File naming - I know that the files in there are not consistent, but instead of 
`/imports/api/transactions/transactions.js` I would prefer
`/imports/api/transactions/schema.js` - it makes it clearer what it is, instead of duplicating the name
- You could rename the files in the other folders too, so that we are consistent (and where they are imported too)

2) Run time - When I run `npm run test:integration:watch` I get an error `There is already a collection named "sessions"` - I presume this is a cut and paste error somewhere

3) I created the branch `sales` for you to start work on, but you have started your branch from the aborted react native branch:

image

There are 2 choices here: a) Mess with the git history to rebase your changes from either `develop` or `sales` b) Merge in changes from `sales` (there may be merge conflicts) and then delete the `sales` folder containing the react native code. No need to re-submit the PR, git will update it for you.

4) You will notice above that the CI tests failed, it's generally good form to make sure that tests run successfully, and you can run them locally to check, eg `npm run  test:integration:watch`

**Comment by mikkelking** [comment]
I spoke too soon, one test is failing, I haven't worked out the problem with that yet but everything else is ok

**Comment by guymcmanusgithub** [comment]
Thanks Mike, I will make the changes you requested above.  I sent an email to your NAB email about branches, and some difficulties i'm having.  Any suggestions?

**Comment by guymcmanusgithub** [comment]
I just pushed the changes mentioned in your comment.  Attempted the optional number 4 - but kept getting a TypeError: Cannot read property of (a bunch of different things depending on what I tried).  I've left my code commented out within the /products/schema.test.js file along with the TypeError that accompanies it if you feel like refactoring it to work.

**Comment by mikkelking** [comment]
FIxed that for you. It was my mistake, a bracket in the wrong place. Git will show you the change if you click on the 'Fix iterable test' above.

I also moved your constants into the `/imports/api/constants` file

Good work! Best use my personal email mikkelking@hotmail.com for anything related to B2B (I don't/can't access NAB emails from home)

**Comment by mikkelking** [comment]
One last thing required, is to update the file CHANGELOG.md, and tick the `Changelog` box at the top of the PR. I did that for you.

**Pull request merged**
